devguide:
  greeting: "Hi Hello~ nice"

---
spring:
  profiles: stage

devguide:
  greeting: "Hi Stage"
---
spring:
  profiles: dev

devguide:
  greeting: "Hi Dev"
---
spring:
  profiles: local

devguide:
  greeting: "Hi Local"
---
